version: "3.7"
services:
  graphql-go-client:
    build:
      dockerfile: $PWD/client.Dockerfile
      context: .
    networks:
      - example
    depends_on:
      - graphql-go-server
  graphql-go-server:
    build:
      dockerfile: $PWD/server.Dockerfile
      context: ../../../../../..
    ports:
      - "8080:8080"
    networks:
      - example
networks:
  example:
